[default.probe]
protocol = "Swd"

[default.general]
chip = "nrf52833_xxAA" # micro:bit v2
# chip = "nrf51822_xxAA" # micro:bit V1

[default.reset]
halt_afterwards = true

[default.rtt]
enabled = false

[default.gdb]
enabled = true
